name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "45.151.133.125:27398"
UUID = "3f233599-1b81-446e-b950-39af92dfdbfb"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
